### ISSUE TITLE
Hi, I want to build statistics and take all the views on one page

### ISSUE THREAD

**Issue by KfirBenShimon** [vanpariyar/wp-post-views#18]
Hello and thank you very much for the help
Is there a shortcode or code that can be used?
I want to display all the views of the posts on the home page

**Comment by KfirBenShimon** [comment]
What does that mean?
Could you maybe help me with this?

**Comment by vanpariyar** [comment]
Yes i can help you with that, so do you want a shortcode for this or other similar thing like Gutenberg block?

**Comment by KfirBenShimon** [comment]
This shortcode would be excellent, what is needed is to see all the views of all the posts, if possible there should be commas after the thousand like 1,000 - 300,000

**Comment by vanpariyar** [comment]
Yes it's possible, but it will be slow. We need some research on that to reduce load on database.

Either we can count on every hour or every 10 minutes so i will be effective.

**Comment by KfirBenShimon** [comment]
If you do that would be great!
I don't care so much if it updates every hour or 10 minutes or as often as possible, the main thing is that in the end it will count automatically :)

**Comment by KfirBenShimon** [comment]
Hi, is there anything new about this?
It would be really great if this option was accessible to everyone :)

**Comment by vanpariyar** [comment]
@KfirBenShimon Thank you for following up for this is in my priority list but could not able to complete as i am on not getting enough time for this.

But i will surly make this feature available soon

**Comment by vanpariyar** [comment]
Hello @KfirBenShimon 

i have added shortcode 

= 1.11 - 19/10/2022 =
- Introduction of the new shortcode

` [WPPV-TOTAL-VIEWS-PER-POST-TYPE post_type="post"]`
