### ISSUE TITLE
Clear cache views on single page

### ISSUE THREAD

**Issue by MrPel96** [vanpariyar/wp-post-views#23]
Hi There,

Is there a way to clear the views from a page? Because when i duplicate an page, the page views are also duplicated with it. But for the new page i would like to set the counter to zero.

Please help

**Comment by MrPel96** [comment]
Hi There,

This is the url where the counter is visible:
https://www.dataction.com/klantverhalen/volvo-cars/

**Comment by MrPel96** [comment]
Hi There, 
Can you provide me with the awnser?

**Comment by vanpariyar** [comment]
Hello, 
@MrPel96 

I suggest removing the copied meta value from the database.

**Comment by vanpariyar** [comment]
Contact ronak@vanpariyar.in if you need more help.

**Comment by MrPel96** [comment]
That does not sound like an easy way to fix the issue :(

**Comment by vanpariyar** [comment]
Hello @MrPel96 

This value is easily editable by the editor. Let me know if you need this help.

**Comment by MrPel96** [comment]
Yes, I would like your help.

**Comment by vanpariyar** [comment]
Don't hesitate to get in touch with ronak@vanpariyar.in
