### ISSUE TITLE
Can we reset counter ?

### ISSUE THREAD

**Issue by houpela** [vanpariyar/wp-post-views#26]
Hi there !
Thanks for your work. it's just perfect for my use. 
Could you tell me if counter coul'd be reset (All counter or maybe by post)? and how i can reset it ?
Could you add this function to your work ?
Thanks

**Comment by houpela** [comment]
Well, i find in database in the postmeta table the metakey 'entry_views' a counter to reset, i reset it from database... 

Could you think it's was possible to put a button to set entry_views to '0' from  your Option Page ?

i'm lookking for it besause i made qr-code with the url of product-post, and your plugin help me to make inventory...

**Comment by vanpariyar** [comment]
Thank you for creating issues i will look into it.

**Comment by vanpariyar** [comment]
Added this to working sprint thanks.
