### ISSUE TITLE
Boa noite

### ISSUE THREAD

**Issue by jrnemesis** [vanpariyar/wp-post-views#38]
aminha visualização na post tá saindo com um zero a mais, tipo tenho a contagem 555 na capa, quando entro fica 5550, como consigo alterar isso por gentileza?

**Comment by vanpariyar** [comment]
Hello @jrnemesis can you please share some details and plugin version you are using ?

**Comment by jrnemesis** [comment]
segue a versão WP Post Views.

Versão 1.16 |WP Post Views.

na capa conta certo
![image](https://github.com/user-attachments/assets/ef2160e3-55c5-4262-af63-5122912dee73)

dentro do post multiplica por 10.
![image](https://github.com/user-attachments/assets/b1605411-48b6-4c51-b916-2c09cd5b3688)

**Comment by jrnemesis** [comment]
Olá, alguém sabe me falar onde consigo alterar?

**Comment by vanpariyar** [comment]
Hello 👋, I am looking on the issue.

**Comment by vanpariyar** [comment]
i am not able to reproduce at my end 😢

**Comment by vanpariyar** [comment]
closing this issue.
